# Generated by Django 4.0.4 on 2022-05-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
